### ISSUE TITLE
condition contexts

### ISSUE THREAD

**Issue by azahnen** [interactive-instruments/xtraserver-plugin-for-hale#15]
Add condition contexts as filters to the mapping. See [AbstractTypeTransformationHandler.java#L109](https://github.com/interactive-instruments/xtraserver-plugin-for-hale/blob/0089e086b9d005610ef44acb5a6d8914eccf1b09/plugins/xtraserver-hale-io/src/main/java/de/ii/xtraserver/hale/io/writer/handler/AbstractTypeTransformationHandler.java#L109).

**example**: `hy-p:Crossing`

**Comment by jechterhoff** [comment]
@azahnen How would the filter to represent a condition context have to look like in the case of a source filter?

Constructed example: If the source type was `o12006` and the filter was defined as `adz='999'`, should the sourcePath then look like: `sourcePath: /o12006{filter=adz = '999'}`?

**Comment by azahnen** [comment]
Yes, that looks correct.
