### ISSUE TITLE
formatted string handler

### ISSUE THREAD

**Issue by azahnen** [interactive-instruments/xtraserver-plugin-for-hale#6]
**class**: [FormattedStringHandler.java](https://github.com/interactive-instruments/xtraserver-plugin-for-hale/blob/master/plugins/xtraserver-hale-io/src/main/java/de/ii/xtraserver/webapi/hale/io/writer/handler/FormattedStringHandler.java)

**plain example**: ???

**object reference example**: `ad:Address/ad:component/xlink:href`

**Comment by jechterhoff** [comment]
Erzeugung von Objektreferenzen wie im [wiki ](https://services.interactive-instruments.de/xtraserver-aaa-suite/wiki/do/view/Arbeitsbereich/P109kAnalyseWebAPI#Antwort_von_ii_vom_14_12_2021)beschrieben umgesetzt.
